### ISSUE TITLE
Seek video using keyboard

### ISSUE THREAD

**Issue by accforgithubtest** [will-moss/erin#6]
Would you please consider adding support for seeking the videos using the right and left arrow keys on the keyboard ?

Currently, I could right click and "Show Controls" to get the seek bar from video player, however there is no way to click on the seek bar.

Also, is it possible to provide a env var to move the video progress indicator to the top instead of the bottom ?

**Comment by will-moss** [comment]
I have just implemented the features you've requested, and I published a new release. You can pull the latest Docker image.

From now on, you should be able to : 
- Put the progress bar at the top using the env variable `PROGRESS_BAR_POSITION=top`
- Seek forward / backward 5 seconds, using the left and right arrows on your keyboard.

Does that work well on your end?

**Comment by accforgithubtest** [comment]
thanks @will-moss, that was really quick ! Both the seek forward / backward as well as the PROGRESS_BAR_POSITION=top are working as expected.

I do notice a new issue when using the seek forward / backward - I am unable to move to the next video (tried using both keyboard / mouse), and going to the previous video also displays the incorrect video. 

Not sure if this is a new issue because of the seek forward feature, or was it probably a old issue that was not yet discovered.

**Comment by will-moss** [comment]
Thanks for your feedback!

Can I ask what browser you're using? Is it on mobile / desktop?

I can't reproduce it on my end. Or I may have to click in the window to focus the page and use the keyboard, but otherwise, the scroll appears to work fine.

**Comment by accforgithubtest** [comment]
I use firefox browser on linux (ubuntu) desktop. 
The issue is inconsistent, not seeing it everytime, but its definitely there sometimes.

**Comment by will-moss** [comment]
Here's a few links I found : 
- https://www.reddit.com/r/Fedora/comments/17s87pn/cannot_seek_back_in_some_videos_on_firefox/
- https://askubuntu.com/questions/1274143/firefox-not-playing-videos-on-ubuntu-20-04-4-lts

I don't even know if they are relevant, but it may help.

Otherwise, if there's a chance you could open the browser dev tools and go to the "Console" tab and check if there are Javascript errors, that would be awesome. Having a Javascript error would be a first steps towards understanding what's happening. Else, maybe try to find a sequence of keys / videos that consistently reproduce the bug, because I don't have access to Ubuntu nor can I reproduce it...

Let me know!

**Comment by accforgithubtest** [comment]
I have tried using the console to try and capture any errors, however, I have not yet seen the same issue again. 
Perhaps we can close this issue, as the Seek feature has now been implemented. 

I primarily use on desktop browser and seek is working on the desktop browser. 
I was attempting to re create the issue on a mobile browser (android + firefox) and noticed there is no way to seek with swipe actions on the mobile browser ? Is the seek expected to work only on desktop browser with keyboard arrow keys ?

**Comment by will-moss** [comment]
Alright, thanks a lot for reporting back.

Regarding the seeking feature on mobile, you're absolutely correct. So far, the feature works with a keyboard, so it works on Desktop only.

Should I implement a double-tap-to-seek-forward/backward feature? So that Desktop and Mobile are on the same page. The same way Youtube handles it (double tap right, and it goes forward 5 seconds).

**Comment by accforgithubtest** [comment]
Yes sure, would be great to have it working on mobile too !

> Should I implement a double-tap-to-seek-forward/backward feature? So that Desktop and Mobile are on the same page. The same way Youtube handles it (double tap right, and it goes forward 5 seconds).

Sounds perfect way to make it work !

**Comment by will-moss** [comment]
Alright, you should be able to pull the latest image, and have it working.

It works by double-tapping the left or right half of the screen.

There is no animation, but it should instantly jump forward / backward 5 seconds.

**Comment by accforgithubtest** [comment]
Just tried it, works as expected and thank you for including this feature in erin ! 
Cheers!
